### ISSUE TITLE
"Get Kodu" link points to dead url

### ISSUE THREAD

**Issue by eanders-ms** [microsoft/KoduGameLab#2]
Some "Get Kodu" links on the kodugamelab website point to a dead url. Microsoft should provide a redirect to the new download site. Example: https://worlds.kodugamelab.com/world/oT7oJhIcy0ahOYhy0zG6vA==

![image](https://user-images.githubusercontent.com/12176807/100498485-62692980-3117-11eb-8c41-c5d616873c06.png)

**Comment by scoy** [comment]
Chris is in the process of replacing this page for the new web site.

**Comment by eanders-ms** [comment]
Any recourse to handle old clients wanting to update, but the dialog takes them to the old product page? I think the MS download site would need to configure a redirect. For the future, it might be a good idea to pass the update url back to the client in the GetCurrentVersion response.
![image](https://user-images.githubusercontent.com/12176807/100526786-0affa380-3181-11eb-9b2c-b7625230dce2.png)

**Comment by scoy** [comment]
I've updated the link.  It should be good now.

**Comment by eanders-ms** [comment]
Oh nice the url is already included. Closing. Thanks scoy!
